package com.gzxz.recruit

/**
 * Generated from `副本公招角色25-12-17.xlsx` by `tools/generate_recruit_data.py`.
 * Do not edit manually; regenerate when the workbook changes.
 */
object GeneratedRecruitData {
    val tagGroups: List<TagGroup> = listOf(
        TagGroup(key = "profession", label = "职业标签", order = 0),
        TagGroup(key = "species", label = "种族标签", order = 1),
        TagGroup(key = "element", label = "属性标签", order = 2),
        TagGroup(key = "terrain", label = "地形标签", order = 3),
    )

    val tags: List<RecruitTag> = listOf(
        RecruitTag(name = "牧师", groupKey = "profession", priority = 211),
        RecruitTag(name = "射手", groupKey = "profession", priority = 207),
        RecruitTag(name = "法师", groupKey = "profession", priority = 206),
        RecruitTag(name = "战士", groupKey = "profession", priority = 200),
        RecruitTag(name = "亡灵", groupKey = "species", priority = 235),
        RecruitTag(name = "神灵", groupKey = "species", priority = 235),
        RecruitTag(name = "器灵", groupKey = "species", priority = 213),
        RecruitTag(name = "魔灵", groupKey = "species", priority = 193),
        RecruitTag(name = "生灵", groupKey = "species", priority = 178),
        RecruitTag(name = "光系", groupKey = "element", priority = 173),
        RecruitTag(name = "火系", groupKey = "element", priority = 172),
        RecruitTag(name = "水系", groupKey = "element", priority = 171),
        RecruitTag(name = "暗系", groupKey = "element", priority = 169),
        RecruitTag(name = "风系", groupKey = "element", priority = 168),
        RecruitTag(name = "地系", groupKey = "element", priority = 165),
        RecruitTag(name = "雪原", groupKey = "terrain", priority = 285),
        RecruitTag(name = "星界", groupKey = "terrain", priority = 235),
        RecruitTag(name = "沙滩", groupKey = "terrain", priority = 173),
        RecruitTag(name = "沙漠", groupKey = "terrain", priority = 165),
        RecruitTag(name = "海洋", groupKey = "terrain", priority = 156),
        RecruitTag(name = "山脉", groupKey = "terrain", priority = 147),
        RecruitTag(name = "森林", groupKey = "terrain", priority = 146),
        RecruitTag(name = "平原", groupKey = "terrain", priority = 143),
    )

    val operators: List<RecruitOperator> = listOf(
        RecruitOperator(name = "军团统领", rarity = 3, tags = setOf("战士", "生灵", "地系", "平原")),
        RecruitOperator(name = "冰蛛女王（限定）", rarity = 3, tags = setOf("射手", "生灵", "水系", "雪原")),
        RecruitOperator(name = "史莱姆王", rarity = 3, tags = setOf("法师", "魔灵", "光系", "森林")),
        RecruitOperator(name = "圣剑之灵", rarity = 3, tags = setOf("战士", "器灵", "光系", "森林")),
        RecruitOperator(name = "地灵使者", rarity = 3, tags = setOf("法师", "生灵", "地系", "平原")),
        RecruitOperator(name = "大地魔女", rarity = 3, tags = setOf("法师", "生灵", "地系", "山脉")),
        RecruitOperator(name = "宁静水灵", rarity = 3, tags = setOf("牧师", "魔灵", "水系", "海洋")),
        RecruitOperator(name = "巨灵之枪", rarity = 3, tags = setOf("战士", "器灵", "地系", "沙漠")),
        RecruitOperator(name = "幽暗龙女", rarity = 3, tags = setOf("战士", "生灵", "暗系", "森林")),
        RecruitOperator(name = "幽灵船长", rarity = 3, tags = setOf("战士", "亡灵", "暗系", "海洋")),
        RecruitOperator(name = "无暇贤者", rarity = 3, tags = setOf("牧师", "生灵", "光系", "沙滩")),
        RecruitOperator(name = "星灵射手", rarity = 3, tags = setOf("射手", "神灵", "光系", "星界")),
        RecruitOperator(name = "星界邪神", rarity = 3, tags = setOf("法师", "神灵", "暗系", "星界")),
        RecruitOperator(name = "林中仙女", rarity = 3, tags = setOf("牧师", "神灵", "光系", "森林")),
        RecruitOperator(name = "核心魔偶", rarity = 3, tags = setOf("战士", "器灵", "地系", "山脉")),
        RecruitOperator(name = "水晶菇娘", rarity = 3, tags = setOf("法师", "生灵", "光系", "山脉")),
        RecruitOperator(name = "淘气恶魔", rarity = 3, tags = setOf("战士", "神灵", "暗系", "森林")),
        RecruitOperator(name = "荒漠猫娘", rarity = 3, tags = setOf("射手", "生灵", "火系", "沙漠")),
        RecruitOperator(name = "蛮牛勇士", rarity = 3, tags = setOf("战士", "生灵", "火系", "平原")),
        RecruitOperator(name = "辰龙", rarity = 3, tags = setOf("战士", "生灵", "风系", "沙滩")),
        RecruitOperator(name = "雪人骑士", rarity = 3, tags = setOf("战士", "魔灵", "水系", "雪原")),
        RecruitOperator(name = "风行游侠", rarity = 3, tags = setOf("射手", "生灵", "风系", "平原")),
        RecruitOperator(name = "魔术大师", rarity = 3, tags = setOf("法师", "生灵", "暗系", "森林")),
        RecruitOperator(name = "鹰身公主", rarity = 3, tags = setOf("射手", "生灵", "风系", "平原")),
        RecruitOperator(name = "黄蜂魔女", rarity = 3, tags = setOf("法师", "生灵", "暗系", "平原")),
        RecruitOperator(name = "黄金之女", rarity = 3, tags = setOf("战士", "魔灵", "光系", "山脉")),
        RecruitOperator(name = "丛林猎手", rarity = 2, tags = setOf("射手", "生灵", "风系", "森林")),
        RecruitOperator(name = "佣兵枪手", rarity = 2, tags = setOf("射手", "生灵", "地系", "沙漠")),
        RecruitOperator(name = "军团铁骑", rarity = 2, tags = setOf("战士", "生灵", "火系", "平原")),
        RecruitOperator(name = "古树妖精", rarity = 2, tags = setOf("法师", "生灵", "地系", "森林")),
        RecruitOperator(name = "哥布林祭祀", rarity = 2, tags = setOf("牧师", "生灵", "风系", "平原")),
        RecruitOperator(name = "啵啵", rarity = 2, tags = setOf("法师", "生灵", "光系", "平原")),
        RecruitOperator(name = "奶糖", rarity = 2, tags = setOf("射手", "生灵", "火系", "平原")),
        RecruitOperator(name = "娜迦射手", rarity = 2, tags = setOf("射手", "生灵", "水系", "海洋")),
        RecruitOperator(name = "孢子女巫", rarity = 2, tags = setOf("法师", "生灵", "地系", "山脉")),
        RecruitOperator(name = "学院导师", rarity = 2, tags = setOf("法师", "生灵", "火系", "森林")),
        RecruitOperator(name = "岩石守卫", rarity = 2, tags = setOf("战士", "魔灵", "地系", "山脉")),
        RecruitOperator(name = "巨大史莱姆", rarity = 2, tags = setOf("战士", "魔灵", "水系", "森林")),
        RecruitOperator(name = "巨岩炮手", rarity = 2, tags = setOf("战士", "魔灵", "地系", "山脉")),
        RecruitOperator(name = "巨魔监工", rarity = 2, tags = setOf("牧师", "生灵", "地系", "山脉")),
        RecruitOperator(name = "幽灵大副", rarity = 2, tags = setOf("战士", "亡灵", "暗系", "海洋")),
        RecruitOperator(name = "恶狼勇士", rarity = 2, tags = setOf("战士", "生灵", "风系", "平原")),
        RecruitOperator(name = "战争祭司", rarity = 2, tags = setOf("牧师", "生灵", "火系", "平原")),
        RecruitOperator(name = "招财", rarity = 2, tags = setOf("牧师", "生灵", "光系", "平原")),
        RecruitOperator(name = "日耀祭司", rarity = 2, tags = setOf("法师", "生灵", "光系", "沙漠")),
        RecruitOperator(name = "星界守卫", rarity = 2, tags = setOf("战士", "神灵", "暗系", "星界")),
        RecruitOperator(name = "月影祭司", rarity = 2, tags = setOf("牧师", "生灵", "暗系", "沙漠")),
        RecruitOperator(name = "植物学者", rarity = 2, tags = setOf("牧师", "生灵", "地系", "森林")),
        RecruitOperator(name = "椰树投手", rarity = 2, tags = setOf("射手", "生灵", "风系", "沙滩")),
        RecruitOperator(name = "水族统领", rarity = 2, tags = setOf("战士", "生灵", "水系", "沙滩")),
        RecruitOperator(name = "波涛守卫", rarity = 2, tags = setOf("战士", "生灵", "水系", "海洋")),
        RecruitOperator(name = "流水法师", rarity = 2, tags = setOf("法师", "魔灵", "水系", "海洋")),
        RecruitOperator(name = "火焰女妖", rarity = 2, tags = setOf("战士", "魔灵", "火系", "山脉")),
        RecruitOperator(name = "爆炸菇娘", rarity = 2, tags = setOf("射手", "生灵", "火系", "山脉")),
        RecruitOperator(name = "牧渔少女", rarity = 2, tags = setOf("法师", "生灵", "水系", "沙滩")),
        RecruitOperator(name = "狂风战士", rarity = 2, tags = setOf("战士", "魔灵", "风系", "平原")),
        RecruitOperator(name = "狩猎勇士", rarity = 2, tags = setOf("战士", "生灵", "火系", "平原")),
        RecruitOperator(name = "狼灵射手", rarity = 2, tags = setOf("射手", "生灵", "地系", "平原")),
        RecruitOperator(name = "疾行闪光", rarity = 2, tags = setOf("战士", "生灵", "光系", "平原")),
        RecruitOperator(name = "破碎剑灵", rarity = 2, tags = setOf("战士", "器灵", "暗系", "森林")),
        RecruitOperator(name = "绿伞菇娘", rarity = 2, tags = setOf("牧师", "生灵", "风系", "山脉")),
        RecruitOperator(name = "翡翠魔偶", rarity = 2, tags = setOf("法师", "器灵", "风系", "山脉")),
        RecruitOperator(name = "胡椒", rarity = 2, tags = setOf("战士", "生灵", "地系", "平原")),
        RecruitOperator(name = "荆棘树妖", rarity = 2, tags = setOf("法师", "生灵", "地系", "森林")),
        RecruitOperator(name = "荒野兽王", rarity = 2, tags = setOf("战士", "生灵", "风系", "平原")),
        RecruitOperator(name = "荒野猎人", rarity = 2, tags = setOf("战士", "生灵", "火系", "沙漠")),
        RecruitOperator(name = "蛮牛剑豪", rarity = 2, tags = setOf("战士", "生灵", "地系", "平原")),
        RecruitOperator(name = "蛮牛祭司", rarity = 2, tags = setOf("牧师", "生灵", "地系", "平原")),
        RecruitOperator(name = "诡秘之影", rarity = 2, tags = setOf("射手", "生灵", "暗系", "平原")),
        RecruitOperator(name = "迷失盾灵", rarity = 2, tags = setOf("战士", "器灵", "光系", "森林")),
        RecruitOperator(name = "鎏金射手", rarity = 2, tags = setOf("射手", "魔灵", "光系", "山脉")),
        RecruitOperator(name = "飓风使者", rarity = 2, tags = setOf("法师", "魔灵", "风系", "平原")),
        RecruitOperator(name = "魂能法师", rarity = 2, tags = setOf("法师", "生灵", "暗系", "森林")),
        RecruitOperator(name = "魔术侍从", rarity = 2, tags = setOf("法师", "生灵", "暗系", "森林")),
        RecruitOperator(name = "鱼人先锋", rarity = 2, tags = setOf("战士", "生灵", "风系", "沙滩")),
        RecruitOperator(name = "兵蜂战士", rarity = 1, tags = setOf("战士", "生灵", "暗系", "平原")),
        RecruitOperator(name = "兵蜂猎手", rarity = 1, tags = setOf("射手", "生灵", "暗系", "平原")),
        RecruitOperator(name = "军团哨兵", rarity = 1, tags = setOf("战士", "生灵", "风系", "平原")),
        RecruitOperator(name = "军团射手", rarity = 1, tags = setOf("射手", "生灵", "风系", "平原")),
        RecruitOperator(name = "军团祭司", rarity = 1, tags = setOf("牧师", "生灵", "风系", "平原")),
        RecruitOperator(name = "史莱姆侍女", rarity = 1, tags = setOf("牧师", "魔灵", "光系", "森林")),
        RecruitOperator(name = "史莱姆战士", rarity = 1, tags = setOf("战士", "魔灵", "火系", "森林")),
        RecruitOperator(name = "史莱姆法师", rarity = 1, tags = setOf("法师", "魔灵", "水系", "森林")),
        RecruitOperator(name = "史莱姆牧师", rarity = 1, tags = setOf("牧师", "魔灵", "地系", "森林")),
        RecruitOperator(name = "哥布林哨兵", rarity = 1, tags = setOf("战士", "生灵", "风系", "平原")),
        RecruitOperator(name = "哥布林战士", rarity = 1, tags = setOf("战士", "生灵", "火系", "平原")),
        RecruitOperator(name = "哥布林法师", rarity = 1, tags = setOf("法师", "生灵", "火系", "平原")),
        RecruitOperator(name = "哥布林猎手", rarity = 1, tags = setOf("射手", "生灵", "风系", "平原")),
        RecruitOperator(name = "大探险家", rarity = 1, tags = setOf("战士", "生灵", "地系", "山脉")),
        RecruitOperator(name = "妖精弓灵", rarity = 1, tags = setOf("射手", "器灵", "风系", "森林")),
        RecruitOperator(name = "孢子卫士", rarity = 1, tags = setOf("战士", "生灵", "地系", "山脉")),
        RecruitOperator(name = "孢子射手", rarity = 1, tags = setOf("射手", "生灵", "风系", "山脉")),
        RecruitOperator(name = "学院学徒", rarity = 1, tags = setOf("法师", "生灵", "地系", "森林")),
        RecruitOperator(name = "学院牧师", rarity = 1, tags = setOf("牧师", "生灵", "光系", "森林")),
        RecruitOperator(name = "巨力少女", rarity = 1, tags = setOf("战士", "生灵", "地系", "平原")),
        RecruitOperator(name = "巨魔守卫", rarity = 1, tags = setOf("战士", "生灵", "地系", "山脉")),
        RecruitOperator(name = "巨魔投手", rarity = 1, tags = setOf("射手", "生灵", "地系", "山脉")),
        RecruitOperator(name = "幽灵枪手", rarity = 1, tags = setOf("射手", "亡灵", "暗系", "海洋")),
        RecruitOperator(name = "幽灵水手", rarity = 1, tags = setOf("战士", "亡灵", "暗系", "海洋")),
        RecruitOperator(name = "星象法师", rarity = 1, tags = setOf("法师", "生灵", "火系", "平原")),
        RecruitOperator(name = "树人守卫", rarity = 1, tags = setOf("战士", "生灵", "地系", "森林")),
        RecruitOperator(name = "武者学徒", rarity = 1, tags = setOf("战士", "生灵", "地系", "森林")),
        RecruitOperator(name = "水族士兵", rarity = 1, tags = setOf("战士", "生灵", "水系", "沙滩")),
        RecruitOperator(name = "沉默猎手", rarity = 1, tags = setOf("战士", "生灵", "风系", "森林")),
        RecruitOperator(name = "游荡人偶", rarity = 1, tags = setOf("战士", "器灵", "暗系", "山脉")),
        RecruitOperator(name = "狼族先知", rarity = 1, tags = setOf("法师", "生灵", "地系", "平原")),
        RecruitOperator(name = "狼族猎手", rarity = 1, tags = setOf("射手", "生灵", "火系", "平原")),
        RecruitOperator(name = "狼灵战士", rarity = 1, tags = setOf("战士", "生灵", "火系", "平原")),
        RecruitOperator(name = "白银歌姬", rarity = 1, tags = setOf("牧师", "魔灵", "光系", "山脉")),
        RecruitOperator(name = "矿洞淘金者", rarity = 1, tags = setOf("战士", "生灵", "地系", "山脉")),
        RecruitOperator(name = "矿洞采集者", rarity = 1, tags = setOf("射手", "生灵", "地系", "山脉")),
        RecruitOperator(name = "荒漠守卫", rarity = 1, tags = setOf("战士", "生灵", "光系", "沙漠")),
        RecruitOperator(name = "荒漠猎手", rarity = 1, tags = setOf("战士", "生灵", "火系", "沙漠")),
        RecruitOperator(name = "荒漠盗贼", rarity = 1, tags = setOf("战士", "生灵", "暗系", "沙漠")),
        RecruitOperator(name = "蓝灵菇娘", rarity = 1, tags = setOf("法师", "生灵", "水系", "山脉")),
        RecruitOperator(name = "蓝鲨教官", rarity = 1, tags = setOf("战士", "生灵", "水系", "海洋")),
        RecruitOperator(name = "贝壳少女", rarity = 1, tags = setOf("射手", "生灵", "水系", "沙滩")),
        RecruitOperator(name = "迷失之魂", rarity = 1, tags = setOf("法师", "亡灵", "暗系", "森林")),
        RecruitOperator(name = "迷幻菇娘", rarity = 1, tags = setOf("牧师", "生灵", "暗系", "山脉")),
        RecruitOperator(name = "遗迹猎人", rarity = 1, tags = setOf("法师", "生灵", "火系", "沙漠")),
        RecruitOperator(name = "野猫猎手", rarity = 1, tags = setOf("射手", "生灵", "地系", "森林")),
        RecruitOperator(name = "银鳞守卫", rarity = 1, tags = setOf("战士", "生灵", "水系", "海洋")),
        RecruitOperator(name = "银鳞鲛姬", rarity = 1, tags = setOf("牧师", "生灵", "水系", "海洋")),
        RecruitOperator(name = "闪灵少女", rarity = 1, tags = setOf("战士", "生灵", "风系", "平原")),
        RecruitOperator(name = "鱼人哨兵", rarity = 1, tags = setOf("战士", "生灵", "水系", "海洋")),
        RecruitOperator(name = "鱼人战士", rarity = 1, tags = setOf("战士", "生灵", "水系", "海洋")),
        RecruitOperator(name = "鱼人祭司", rarity = 1, tags = setOf("牧师", "生灵", "水系", "海洋")),
        RecruitOperator(name = "鹰身少女", rarity = 1, tags = setOf("战士", "生灵", "风系", "平原")),
    )
}
